### ISSUE TITLE
Ripple scroll with body content 

### ISSUE THREAD

**Issue by palashkaria** [tungv/rippl#3]
Hey,
I see a bug here: if you scroll immediately after click, the ripple scroll down (because it was rendered in body). 

One way to fix this would be to render the ripple it in the component itself (instead of the body).

**Comment by tungv** [comment]
Thank you for your report. The reason it's rendered in the body is because not every HTML elements allow arbitrary div tag as a child node. Eg. the tbody, it just doesn't let you insert a div in between 2 tr's or a ul > li relationship. I'm not sure both rippling and immediately scrolling away is a good combination btw

**Comment by palashkaria** [comment]
@tungv I appriciate you supporting all kinds of elements & also taking care of w3c spces. But imagine a use case where clicking on a button causes something to _slide down_, something like this: 
<img width="567" alt="screenshot 2019-02-10 at 9 12 26 pm" src="https://user-images.githubusercontent.com/2976363/52535788-a2abbc00-2d78-11e9-865b-93210ce396f3.png">

Maybe it could be a simple boolean option in the lib, just something like 'renderToComponent={true}', to handle such use cases?

**Comment by tungv** [comment]
I like your idea of having an option. However it might need some different approach in implementation. You may have to copy the code (only one single file) into your code base and play with it. I believe removing createPortal line and changing fixed position to absolute would do it, but I'm just not sure
